In [73]:
import numpy as np
import pandas as pd
import mglearn
import matplotlib.pyplot as plt

In [74]:
data=pd.read_csv("adult.data",header=None, index_col=False,names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','gender','capital-gain','capital-loss','hours-per-week','native-country','income'] )
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [75]:
print(data.gender.value_counts())

 Male      21790
 Female    10771
Name: gender, dtype: int64

In [76]:
features=['age','workclass','education','gender','hours-per-week','occupation']
x=pd.get_dummies(data[features])
yd=pd.get_dummies(data['income'])
x.head()

,age,hours-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,...,occupation_ Farming-fishing,occupation_ Handlers-cleaners,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving
0,39,40,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,50,13,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,38,40,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,53,40,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,28,40,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [77]:
y=yd[' >50K'].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)

In [84]:
from sklearn.neighbors import KNeighborsClassifier
kc=KNeighborsClassifier(n_neighbors=3)
kc.fit(x_train,y_train)
print("Training score:\n{:.2f}".format(kc.score(x_train,y_train)))
print("Testing score:\n{:.2f}".format(kc.score(x_test,y_test)))

Training score:
0.86
Testing score:
0.77

In [78]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression(C=10000)
logreg.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=10000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [79]:
print("Training score:\n{:.2f}".format(logreg.score(x_train,y_train)))
print("Testing score:\n{:.2f}".format(logreg.score(x_test,y_test)))

Training score:
0.81
Testing score:
0.82

In [80]:
from sklearn.ensemble import RandomForestClassifier
# print("{}".format(list(x_train.columns)))
clf=RandomForestClassifier(n_estimators=1000,random_state=20,max_depth=7,max_features=8)
clf.fit(x_train,y_train)
print("Training score:\n{:.2f}".format(clf.score(x_train,y_train)))
print("Testing score:\n{:.2f}".format(clf.score(x_test,y_test)))

Training score:
0.82
Testing score:
0.81

In [81]:
from sklearn.ensemble import GradientBoostingClassifier
gbrt=GradientBoostingClassifier(random_state=23)
gbrt.fit(x_train,y_train)
print("Training score:\n{:.2f}".format(gbrt.score(x_train,y_train)))
print("Testing score:\n{:.2f}".format(gbrt.score(x_test,y_test)))

Training score:
0.82
Testing score:
0.82